import { useMemo } from 'react'; import { Card, StatCard } from '../components/UI'; import { IconAlert, IconCheck, IconList, IconMoney } from '../components/Icons'; import { formatMoney } from '../lib/utils'; import { invoiceMetrics } from '../lib/metrics'; import { SLA_DAYS, ageDays, STAGE_LABELS } from '../lib/workflow'; import { DonutChart, HorizontalBarChart } from '../components/Charts';
export default function AdminDashboard({receptions=[],officers=[]}){
  const m=useMemo(()=>invoiceMetrics(receptions,officers),[receptions,officers]);
  const delayed=useMemo(()=>receptions.filter(r=>!r.verifiedAt&&ageDays(r.submittedToHqAt||r.receivedAt)>SLA_DAYS).slice(0,10),[receptions]);
  const stageData=useMemo(()=>[
    {name:STAGE_LABELS.hq_reception,value:m.stageCounts.hq_reception},
    {name:STAGE_LABELS.verification,value:m.stageCounts.verification},
    {name:STAGE_LABELS.finance,value:m.stageCounts.finance},
  ],[m]);
  const workloadData=useMemo(()=>m.officerStats.slice(0,8).map(s=>({name:s.officer.name,value:s.pending})),[m]);
  return <div className="p-4 md:p-8 max-w-7xl"><header className="mb-6"><h1 className="font-display text-2xl md:text-3xl font-medium text-rssb-blue-dark">Verification Lead Control Center</h1><p className="text-sm text-gray-500 mt-1">Assign workload, protect the 15-day verification SLA, and identify where delays are accumulating.</p></header><div className="grid grid-cols-2 md:grid-cols-6 gap-3 mb-6"><StatCard label="Open" value={m.open.length} sub="not yet verified" accent="blue" icon={IconList}/><StatCard label="Ready to assign" value={receptions.filter(r=>r.status==='ready_for_assignment').length} sub="clean reception records" accent="teal" icon={IconCheck}/><StatCard label="Over 15 days" value={m.overdue} sub="SLA breaches" accent="red" icon={IconAlert}/><StatCard label="SLA met" value={`${m.slaRate}%`} sub="of completed verification" accent="teal" icon={IconCheck}/><StatCard label="Billed" value={formatMoney(m.billed)} sub="RWF all records" accent="gold" icon={IconMoney}/><StatCard label="Deduction" value={formatMoney(m.deductions)} sub="identified in verification" accent="gold" icon={IconMoney}/></div>
  <div className="grid lg:grid-cols-2 gap-4 mb-6">
    <DonutChart data={stageData} title="Pipeline" sub={`${m.total} total`} />
    <HorizontalBarChart data={workloadData} dataKey="value" name="Open items" title="Officer workload (top 8)" color="#0d7a70" />
  </div>
  <Card className="p-5 mb-6"><h2 className="font-semibold mb-4">Officer workload & performance</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs uppercase text-gray-400"><tr><th className="text-left">Officer</th><th className="text-right">Open</th><th className="text-right">Done</th><th className="text-right">Voucher %</th><th className="text-right">SLA</th></tr></thead><tbody className="divide-y">{m.officerStats.slice(0,10).map(s=><tr key={s.officer.id}><td className="py-2">{s.officer.name}</td><td className="text-right">{s.pending}</td><td className="text-right">{s.completed}</td><td className="text-right">{s.voucherRate}%</td><td className="text-right">{s.breaches===0?'On track':`${s.breaches} breach`}</td></tr>)}</tbody></table></div></Card>
  <Card className="overflow-x-auto"><div className="px-4 py-3 border-b font-semibold">Overdue invoices — intervene by root-cause</div><table className="w-full text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="text-left px-4 py-2">Invoice</th><th className="text-left px-4 py-2">Facility</th><th className="text-left px-4 py-2">Stage</th><th className="text-right px-4 py-2">Age</th><th className="text-left px-4 py-2">Delay reason</th></tr></thead><tbody className="divide-y">{delayed.map(r=><tr key={r.id}><td className="px-4 py-2 font-mono text-xs">{r.receiptNo}</td><td className="px-4 py-2">{r.facilityName}</td><td className="px-4 py-2">{r.status.replaceAll('_',' ')}</td><td className="px-4 py-2 text-right text-rose-600">{ageDays(r.submittedToHqAt||r.receivedAt)}d</td><td className="px-4 py-2">{r.delayReason||'No reason captured'}</td></tr>)}{!delayed.length&&<tr><td colSpan="5" className="py-8 text-center text-gray-400">No current SLA breaches.</td></tr>}</tbody></table></Card></div>}
